// <auto-generated />
namespace OopRestaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class setMenuitemNamecolumntorequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setMenuitemNamecolumntorequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201902021141340_set Menuitem.Name column to required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
