// <auto-generated />
namespace OopRestaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class setMenuitemNamemaxlengthto200 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setMenuitemNamemaxlengthto200));
        
        string IMigrationMetadata.Id
        {
            get { return "201902021148275_set Menuitem.Name maxlength to 200"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
