// <auto-generated />
namespace RestaurantProjectWebV02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddMenuItemstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMenuItemstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201903170925115_Add MenuItems table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
