// <auto-generated />
namespace RestaurantProjectWebV02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetMenuItemsNamemaxlengthto200 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetMenuItemsNamemaxlengthto200));
        
        string IMigrationMetadata.Id
        {
            get { return "201903170939527_Set MenuItems.Name maxlength to 200"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
